language: python
python:
# - "2.6"
  - "2.7"
#  - "3.3"
#  - "3.4"
#  - "3.5"
#  - "3.5-dev"  # 3.5 development branch
  - "3.6"
#  - "3.6-dev"  # 3.6 development branch
env:
#  - DJANGO_VERSION=1.10.8
#  - DJANGO_VERSION=1.11.5
  - NUMPY_VERSION=1.11.0
#  - NUMPY_VERSION=1.12.1
  - NUMPY_VERSION=1.14.0
# command to install dependencies
install:
  - pip install -q numpy==$NUMPY_VERSION
  - pip install -r requirements.txt
  - python setup.py -q install
# command to run tests
script:
  - pytest
