
print(int(3.5))
print(float(3))
print(str(5))
print("-------------------------------------------------------------    ")
x = int(3.5)
y =float(3)
z = str(5)
print(x)
print(type(x))
print(type(y))
print(type(z))